sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache:
  directories:
    - node_modules
branches:
  only:
    - master # build master branch only

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo version
  - hexo clean
  - hexo generate # generate static files



after_script:
  - git config user.name "all3n"
  - git config user.email "wanghch8398@163.com"
  - sed -i "s#git@github.com:#https://${GH_TOKEN}@github.com/#g" ./_config.yml
  - sed -i "s#baidu_token#${BAIDU_TOKEN}#g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
